/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/portfolio-model/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_portfolio_model__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DrillingMethod
         * @enum {string}
         */
        DrillingMethod: "diagonal" | "normal" | "not_possible" | "unknown";
        /** PortfolioAnalysisError */
        PortfolioAnalysisError: {
            /** Building Id */
            BUILDING_id: string;
            /** Error */
            error: string;
        };
        /** PortfolioAnalysisResult */
        PortfolioAnalysisResult: {
            /** Building Address */
            BUILDING_address: string;
            /** Building Area Km2 */
            BUILDING_area_km2: number;
            /** Building Area M2 */
            BUILDING_area_m2: number;
            /** Building Construction Decade */
            BUILDING_construction_decade: number;
            /** Building Electricity Mwh */
            BUILDING_electricity_mwh: number;
            /** Building Footprint Sqm */
            BUILDING_footprint_sqm: number | null;
            /** Building Groundwater Area */
            BUILDING_groundwater_area: boolean | null;
            /** Building Heat Mwh */
            BUILDING_heat_mwh: number;
            /** Building Heat Peak Power */
            BUILDING_heat_peak_power: number;
            /** Building Id */
            BUILDING_id: string;
            /** Building Lot Sqm */
            BUILDING_lot_sqm: number | null;
            /** Building Number Of Floors */
            BUILDING_number_of_floors: number | null;
            /** Building Type */
            BUILDING_type: string;
            /** Building Underground Zoning */
            BUILDING_underground_zoning: boolean | null;
            /** Building Ventilation Units */
            BUILDING_ventilation_units: number;
            /** Dh Co2 */
            DH_co2: number;
            /** Dh Total Energy Eur */
            DH_total_energy_eur: number;
            /** Dh Heat Recovery Captured Energy Mwh */
            DH_HEAT_RECOVERY_captured_energy_mwh: number;
            /** Dh Heat Recovery Dh Eur */
            DH_HEAT_RECOVERY_dh_eur: number;
            /** Dh Heat Recovery Dh Mwh */
            DH_HEAT_RECOVERY_dh_mwh: number;
            /** Dh Heat Recovery Hp Electricity Eur */
            DH_HEAT_RECOVERY_hp_electricity_eur: number;
            /** Dh Heat Recovery Hp Electricity Mwh */
            DH_HEAT_RECOVERY_hp_electricity_mwh: number;
            /** Dh Heat Recovery Hp Total Mwh */
            DH_HEAT_RECOVERY_hp_total_mwh: number;
            /** Dh Heat Recovery Capex */
            DH_HEAT_RECOVERY_capex: number;
            /** Dh Heat Recovery Co2 */
            DH_HEAT_RECOVERY_co2: number;
            /** Dh Heat Recovery Elec Upgrade Capex */
            DH_HEAT_RECOVERY_elec_upgrade_capex: number;
            /** Dh Heat Recovery Hp Power */
            DH_HEAT_RECOVERY_hp_power: number;
            /** Dh Heat Recovery Irr */
            DH_HEAT_RECOVERY_irr: number;
            /** Dh Heat Recovery Opex */
            DH_HEAT_RECOVERY_opex: number;
            /** Dh Heat Recovery Pmt */
            DH_HEAT_RECOVERY_pmt: number;
            /** Dh Heat Recovery Pp */
            DH_HEAT_RECOVERY_pp: number | null;
            /** Gs Borehole Count */
            GS_borehole_count: number;
            /** Gs Borehole Mwh */
            GS_borehole_mwh: number;
            /** Gs Borehole Sqm */
            GS_borehole_sqm: number;
            /** Gs Capex */
            GS_capex: number;
            /** Gs Co2 */
            GS_co2: number;
            /** Gs Drill Depth Per Borehole */
            GS_drill_depth_per_borehole: number;
            GS_drill_method: components["schemas"]["DrillingMethod"];
            /** Gs Drillcost */
            GS_drillcost: number;
            /** Gs Elec Upgrade Capex */
            GS_elec_upgrade_capex: number;
            /** Gs Electric Boiler Power */
            GS_electric_boiler_power: number;
            /** Gs Hp Power */
            GS_hp_power: number;
            /** Gs Hp Electricity Eur */
            GS_hp_electricity_eur: number;
            /** Gs Hp Electricity Mwh */
            GS_hp_electricity_mwh: number;
            /** Gs Irr */
            GS_irr: number | null;
            /** Gs Opex */
            GS_opex: number | null;
            /** Gs Pmt */
            GS_pmt: number;
            /** Gs Pp */
            GS_pp: number | null;
            /** Gs Heat Recovery Borehole Count */
            GS_HEAT_RECOVERY_borehole_count: number;
            /** Gs Heat Recovery Borehole Mwh */
            GS_HEAT_RECOVERY_borehole_mwh: number;
            /** Gs Heat Recovery Borehole Sqm */
            GS_HEAT_RECOVERY_borehole_sqm: number;
            /** Gs Heat Recovery Capex */
            GS_HEAT_RECOVERY_capex: number;
            /** Gs Heat Recovery Co2 */
            GS_HEAT_RECOVERY_co2: number;
            /** Gs Heat Recovery Drill Depth Per Borehole */
            GS_HEAT_RECOVERY_drill_depth_per_borehole: number;
            GS_HEAT_RECOVERY_drill_method: components["schemas"]["DrillingMethod"];
            /** Gs Heat Recovery Drillcost */
            GS_HEAT_RECOVERY_drillcost: number;
            /** Gs Heat Recovery Elec Upgrade Capex */
            GS_HEAT_RECOVERY_elec_upgrade_capex: number;
            /** Gs Heat Recovery Hp Electricity Eur */
            GS_HEAT_RECOVERY_hp_electricity_eur: number;
            /** Gs Heat Recovery Hp Electricity Mwh */
            GS_HEAT_RECOVERY_hp_electricity_mwh: number;
            /** Gs Heat Recovery Irr */
            GS_HEAT_RECOVERY_irr: number | null;
            /** Gs Heat Recovery Opex */
            GS_HEAT_RECOVERY_opex: number | null;
            /** Gs Heat Recovery Pmt */
            GS_HEAT_RECOVERY_pmt: number;
            /** Gs Heat Recovery Pp */
            GS_HEAT_RECOVERY_pp: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_model_portfolio_model__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalysisResult"] | components["schemas"]["PortfolioAnalysisError"] | null;
                };
            };
        };
    };
}
